### ISSUE TITLE
what the mean of "TMAPs" ??

### ISSUE THREAD

**Issue by mapengsen** [undeadpixel/scaffold-decorator-tmap-scripts#1]
Scripts to generate TMAPs
This repository holds the scripts to generate the TMAPs from the manuscript "SMILES-based deep generative scaffold decorator for de-novo drug design".

can you give a explain of "TMAPs"

**Comment by undeadpixel** [comment]
Hi!

Please have a look at the official paper about TMAPs to get an idea of what are they.

Official website: https://tmap.gdb.tools/
Paper: https://jcheminf.biomedcentral.com/articles/10.1186/s13321-020-0416-x

Hope it helps!

Josep

**Comment by mapengsen** [comment]
Thank you very much!
